name: Weekly Signal Report Email

on:
  schedule:
    - cron: '0 12 * * 1'  # Every Monday at noon UTC
  workflow_dispatch:

jobs:
  email-report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install yfinance pandas python-dotenv fredapi

      - name: Send Weekly Market Signal Email
        run: python weekly_report.py
